version: '3.7'

services:
  db:
    image: postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data

    environment:
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    ports:
      - "5432:5432"
      
  redis:
    image: "redis:latest"
    ports:
      - "6379:6379"

  web:
    build: .
    user: django
    stdin_open: true # docker run -i
    tty: true        # docker run -t
    command: gunicorn backend.transcendence.wsgi:application --bind 0.0.0.0:8000
    volumes:
      - .:/usr/src/app
      - avatars:/usr/src/app/avatars
    ports:
      - "8000:8000"
    depends_on:
      - db 
    environment:
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - DJANGO_SECRET_KEY=${DJANGO_SECRET_KEY}
      - DJANGO_SETTINGS_MODULE=transcendence.settings
      - PYTHONPATH=/usr/src/app/backend
      
  nginx:
    image: nginx:latest
    volumes:
      - ./nginx:/etc/nginx/conf.d
      - ./nginx/ssl:/etc/nginx/ssl
      - ./static:/usr/share/nginx/html/static
      - ./media:/usr/share/nginx/html/media
      - ./frontend:/usr/share/nginx/html
    ports:
      - "443:443"
    depends_on:
      - web




volumes:
  postgres_data:
  avatars:
  static:
  media:
