version: '3.7'

services:
  db:
    image: postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data

    environment:
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    ports:
      - "5432:5432"
    options: >-
      --health-cmd pg_isready
      --health-interval 10s
      --health-timeout 5s
      --health-retries 5

  web:
    build: .
    user: django
    stdin_open: true # docker run -i
    tty: true        # docker run -t
    command: python backend/manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/usr/src/app
      - avatars:/usr/src/app/avatars
    ports:
      - "8000:8000"
    depends_on:
      - db 
    environment:
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - DJANGO_SECRET_KEY=${DJANGO_SECRET_KEY}

  
volumes:
  postgres_data:
  avatars:
