services:
  db:
    image: postgres
    volumes:
      - postgres:/goinfre/var/lib/postgresql/data

    environment:
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    networks:
      - transcendence
      
  redis:
    image: "redis:latest"
    networks:
      - transcendence

  web:
    build: web
    user: django
    command: ["./entrypoint.sh", "db", "python", "backend/manage.py", "runserver", "0.0.0.0:8000"]
    volumes:
      - ./web:/goinfre/usr/src/app # for dev remove for correction
      - ./tests:/goinfre/usr/src/app/tests # for dev remove for correction
      - static:/goinfre/usr/src/app/static
      - avatars:/goinfre/usr/src/app/avatars
    networks:
      - transcendence
    ports:
      - "8000:8000"
    depends_on:
      - db 
    environment:
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - DJANGO_SECRET_KEY=${DJANGO_SECRET_KEY}
      
  nginx:
    image: nginx:latest
    volumes:
      - ./nginx:/goinfre/etc/nginx/conf.d
      - ./nginx/ssl:/goinfre/etc/nginx/ssl
      - static:/goinfre/usr/share/nginx/html/static
    networks:
      - transcendence
    ports:
      - "8443:8443"
    depends_on:
      - web

networks:
  transcendence:
    driver: bridge
  
volumes:
  postgres:
  avatars:
  static:
    driver: local
    driver_opts:
      type: none
      device: ./static/
      o: bind
