name: Transcendence CI

on: [push, pull_request]

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Set .env file
      run: cp .env.example .env

    - name: Build and run Docker Compose
      run: make

    - name: Run PyTest
      run: docker compose exec -T web pytest backend -c tests/pytest.ini

    - name: Shutdown Docker Compose
      if: always()
      run: make fclean
