name: Transcendence CI

on:
  push:
    branches:
      - '*'
  pull_request:
    branches:
      - master

jobs:
  docker:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Build and start containers
      run: docker-compose up -d --build
      working-directory: ./
      run: sleep 10

    - name : Check containers
      run: docker ps | grep ft_transcendence_web 
      run: docker ps | grep ft_transcendence_db
  

  django:
    - name: Run tests
      run: docker-compose exec web pytest

      run: docker-compose down --volumes