name: Transcendence CI

on:
  push:
    branches:
      - '*'
  pull_request:
    branches:
      - master

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Build and start containers
      run: |
        docker-compose up -d --build
        sleep 10
      working-directory: ./

  django:
    needs: docker
    runs-on: ubuntu-latest
    steps:
    - name: Run tests and bring down containers
      run: docker-compose exec web pytest backend