name: Transcendence CI

on: [push, pull_request]

jobs:
  docker:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Build and start containers
      run: docker-compose up -d --build
      working-directory: ./

    - name : Wait for containers to start
      run: sleep 10

    - name : Check web container
      run: docker ps | grep ft_transcendence_web 
    
    - name : Check db container
      run: docker ps | grep ft_transcendence_db
      
  django:
    - name: Run tests
      run: docker-compose exec web pytest
      
    - name: Clean up
      run: docker-compose down --volumes