name: Transcendence CI

on: [push, pull_request]

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Build and run Docker Compose
      run: docker-compose up -d --build

    - name: Run Django migrations
      run: docker-compose exec web python manage.py migrate

    - name: Run PyTest
      run: docker-compose exec web pytest backend/

    - name: Lint Python Code
      uses: psf/black@stable
      with:
        args: --check backend/

    - name: Check for JS vulnerabilities
      run: |
        npm install
        npm audit

    - name: Lint JavaScript Code
      run: |
        npm install eslint
        eslint static/js/

    - name: Shutdown Docker Compose
      run: docker-compose down
