name: Transcendence CI

on: [push, pull_request]

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Set .env file
      run: cp .env.example .env

    - name: Build and copy PyTest configuration
      run: make && docker compose cp tests/pytest.ini web:/usr/src/app

    - name: PyTest
      run: docker compose exec -T web pytest backend

    - name: Show logs
      if: failure()
      run: docker compose logs
      
    - name: Shutdown Docker Compose
      if: always()
      run: make fclean
